export const actionTypes = {
  TRIP_TYPE_OPTION_CHANGE: "TRIP_TYPE_OPTION_CHANGE",
  DEPARTURE_AIRPORT_CHANGE: "DEPARTURE_AIRPORT_CHANGE",
  DESTINATION_AIRPORT_CHANGE: "DESTINATION_AIRPORT_CHANGE"
};
