export const actionTypes = {
  TRIP_TYPE_OPTION_CHANGE: "TRIP_TYPE_OPTION_CHANGE",
  DEPARTURE_AIRPORT_CHANGE: "DEPARTURE_AIRPORT_CHANGE",
  DESTINATION_AIRPORT_CHANGE: "DESTINATION_AIRPORT_CHANGE",
  DEPARTURE_DATE_CHANGE: "DEPARTURE_DATE_CHANGE",
  RETURN_DATE_CHANGE: "RETURN_DATE_CHANGE",
  ADD_PASSENGER: "ADD_PASSENGER",
  DELETE_PASSENGER: "DELETE_PASSENGER",
  CHANGE_SEAT_SELECTION: "CHANGE_SEAT_SELECTION",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_ERRORS: "GET_ERRORS"
};
